### ISSUE TITLE
Stopping dmwappushservice will break Intune/MDM management

### ISSUE THREAD

**Issue by gonzague** [RedAndBlueEraser/windows-10-enhance-2#1]
Hello just FYI, these two lines :

`sc.exe stop dmwappushservice
sc.exe config dmwappushservice start= disabled`

will break Intune management of devices so not ideal :) the machines won't report anymore to the company

**Comment by RedAndBlueEraser** [comment]
Thanks for picking up this issue. I haven't used Microsoft Intune myself.

On further investigation, I don't think dmwappushservice is used by Microsoft for telemetry data collection, so I have removed the code to disable the service.

My script only disables but doesn't remove this service, so the user can re-enable the service by:
`sc.exe config dmwappushservice start= demand`

If the service was removed, then I believe the user can re-add the service by following the fix on https://call4cloud.nl/2022/11/intune-sync-issue-dmwappushservice-missing/#part5
